/*DETALHAMENTO*/
SELECT
ITSVLRDEBICMS AS DEB_ICMS,
ITSVLRICMS AS ALIQ,
ITSBASCAL AS BASE_ICMS,
TRBID AS TRIB,
TRBIDVDA AS TRIB_VENDA, 
ITSSITTRB AS CST,*
FROM ITEM_SAIDA
WHERE LOJCOD = '000002'
AND ITSTIP = 'E'
AND ITSDOCDATEMI = '2019/04/10'
AND ITSSAINUMEQP = '006'
AND ITSDOCTIP = 'PDV'
AND SUBSTRING(TRBID, 1, 1) = 'R'
--AND TRBID =''

/*ALTERAÇÃO PARA FONTE*/
BEGIN TRAN
UPDATE ITEM_SAIDA SET
ITSSITTRB = '60', TRBID = 'F00', ITSBASCAL = 0
WHERE LOJCOD = '000002'
AND ITSTIP = 'E'
AND ITSDOCDATEMI = '2019/04/10'
AND ITSSAINUMEQP = '006'
AND ITSDOCTIP = 'PDV'
--AND SUBSTRING(TRBID, 1, 1) = 'R'
AND TRBID = 'T01'

/*ALTERAÇÃO PARA TRIBUTADO*/
BEGIN TRAN
UPDATE ITEM_SAIDA SET
ITSSITTRB = '00'
WHERE LOJCOD = '000002'
AND ITSTIP = 'E'
AND ITSDOCDATEMI = '2019/04/10'
AND ITSSAINUMEQP = '006'
AND ITSDOCTIP = 'PDV'
AND SUBSTRING(TRBID, 1, 1) = 'R'


--COMMIT

/*CONSULTA ITEM SAIDA*/
SELECT
ITSVLRDEBICMS,
ITSBASCAL,
TRBID,
TRBIDVDA,
ITSSITTRB,
ITSVLRICMS,*
FROM ITEM_SAIDA
WHERE LOJCOD = '000002'
AND SAICOD = 777425
AND REFPLU = '039369'
AND ITSSEQ = 31

/*TOTALIZADOR POR TRIBUTAÇÃO*/
SELECT
ITSVLRICMS AS ALIQ,
SUM (ITSBASCAL) AS BASE_ICMS,
CASE
TRBID
WHEN 'F00' THEN 'FONTE'
WHEN 'T01' THEN 'FONTE'
WHEN 'T18' THEN 'TRIBUTADO'
WHEN 'T12' THEN 'TRIBUTADO'
WHEN 'R33' THEN 'TRIBUTADO' 
WHEN 'R61' THEN 'TRIBUTADO'END AS TRIB_VENDA,
ITSSITTRB AS CST
FROM ITEM_SAIDA
WHERE LOJCOD = '000002'
AND ITSTIP = 'E'
AND ITSDOCDATEMI = '2019/04/10'
AND ITSSAINUMEQP = '006'
AND ITSDOCTIP = 'PDV'
AND (SUBSTRING(TRBID, 1, 1)
      IN ('T', 'R', 'F'))
GROUP BY ITSVLRICMS, TRBID,ITSSITTRB
ORDER BY 1


