SELECT
  LOJ.LOJCOD,
  ISNULL(CONSULTA_INVENTARIO.PENDENCIA, 0) AS INVENTARIO,
  ISNULL(CONSULTA_AJUSTE.PENDENCIA, 0) AS AJUSTE,
  ISNULL(CONSULTA_QUEBRA.PENDENCIA, 0) AS QUEBRA,
  ISNULL(CONSULTA_TROCA.PENDENCIA, 0) AS TROCA,
  ISNULL(CONSULTA_DEVOLUCAO.PENDENCIA, 0) AS DEVOLUCAO,
  ISNULL(CONSULTA_REQUISICAO_CONSUMO.PENDENCIA, 0) AS REQUISICAO_CONSUMO,
  ISNULL(CONSULTA_PRODUCAO_COMPOSTO.PENDENCIA, 0) AS PRODUCAO_COMPOSTO,
  ISNULL(CONSULTA_RENDIMENTO.PENDENCIA, 0) AS PRODUCAO_RENDIMENTO
FROM V_LOJA LOJ
LEFT JOIN (SELECT
  LOJCOD,
  COUNT(INVCOD) AS PENDENCIA
FROM (SELECT
  INVENTARIO.LOJCOD,
  INVENTARIO.INVCOD
FROM INVENTARIO
INNER JOIN ITEM_INVENTARIO
  ON INVENTARIO.INVCOD = ITEM_INVENTARIO.INVCOD
INNER JOIN REFERENCIA
  ON REFERENCIA.REFPLU = ITEM_INVENTARIO.REFPLU
INNER JOIN AJUSTE
  ON AJUSTE.AJUCOD = ITEM_INVENTARIO.AJUCOD
  AND AJUSTE.LOJCOD = INVENTARIO.LOJCOD
  AND AJUSTE.LOCCOD = INVENTARIO.LOCCOD
  AND AJUSTE.LOJCOD = INVENTARIO.LOJCOD
WHERE (REFERENCIA.REFCMP <> 'K')
AND (INVENTARIO.INVDATABE BETWEEN '2019/10/28' AND '2019/11/27')
AND AJUQTD > 0
AND ((INVTIPESTCNG = 'F')
OR (INVTIPESTCNG = 'A'
AND INVAJUESTFSC = 'S'))
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL
WHERE ESTOQUE_NOTA_FISCAL.LOJCOD = INVENTARIO.LOJCOD
AND ESTOQUE_NOTA_FISCAL.LOCCOD = INVENTARIO.LOCCOD
AND ESTOQUE_NOTA_FISCAL.INVCOD = INVENTARIO.INVCOD
AND ESTOQUE_NOTA_FISCAL.INVCOD = ITEM_INVENTARIO.INVCOD
AND ESTOQUE_NOTA_FISCAL.REFPLU = ITEM_INVENTARIO.REFPLU)
GROUP BY INVENTARIO.LOJCOD,
         INVENTARIO.INVCOD) AS CONSULTA_INVENTARIO
GROUP BY CONSULTA_INVENTARIO.LOJCOD) AS CONSULTA_INVENTARIO
  ON CONSULTA_INVENTARIO.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  AJUSTE.LOJCOD,
  COUNT(REFERENCIA.REFPLU) AS PENDENCIA
FROM AJUSTE
INNER JOIN REFERENCIA
  ON AJUSTE.REFPLU = REFERENCIA.REFPLU
INNER JOIN TIPO_OPERACAO_ESTOQUE
  ON TIPO_OPERACAO_ESTOQUE.TOECOD = AJUSTE.TOECOD
WHERE (AJUSTE.AJUDAT BETWEEN '2019/10/28' AND '2019/11/27')
AND (TIPO_OPERACAO_ESTOQUE.TOETIP = 'A')
AND AJUQTD > 0
AND NOT EXISTS (SELECT
  *
FROM ITEM_INVENTARIO
WHERE AJUSTE.AJUCOD = ITEM_INVENTARIO.AJUCOD)
AND NOT EXISTS (SELECT
  *
FROM EXTRATO_ESTOQUE
WHERE AJUSTE.AJUCOD = EXTRATO_ESTOQUE.AJUCOD
AND EXTRATO_ESTOQUE.ORICOD = '117')
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL
WHERE ESTOQUE_NOTA_FISCAL.AJUCOD = AJUSTE.AJUCOD)
GROUP BY AJUSTE.LOJCOD) AS CONSULTA_AJUSTE
  ON CONSULTA_AJUSTE.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  AJUSTE.LOJCOD,
  COUNT(REFERENCIA.REFPLU) AS PENDENCIA
FROM AJUSTE
INNER JOIN REFERENCIA
  ON AJUSTE.REFPLU = REFERENCIA.REFPLU
INNER JOIN TIPO_OPERACAO_ESTOQUE
  ON TIPO_OPERACAO_ESTOQUE.TOECOD = AJUSTE.TOECOD
WHERE (AJUSTE.AJUDAT BETWEEN '2019/10/28' AND '2019/11/27')
AND (TIPO_OPERACAO_ESTOQUE.TOETIP = 'Q')
AND NOT EXISTS (SELECT
  *
FROM ITEM_INVENTARIO
WHERE AJUSTE.AJUCOD = ITEM_INVENTARIO.AJUCOD)
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL
WHERE ESTOQUE_NOTA_FISCAL.AJUCOD = AJUSTE.AJUCOD)
GROUP BY AJUSTE.LOJCOD) AS CONSULTA_QUEBRA
  ON CONSULTA_QUEBRA.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  LOJCOD,
  COUNT(*) AS PENDENCIA
FROM (SELECT
  DOCUMENTO.DOCCOD,
  DOCUMENTO.LOJCOD
FROM DOCUMENTO
INNER JOIN DEVOLUCAO
  ON (DOCUMENTO.LOJCOD = DEVOLUCAO.LOJCOD)
  AND (DOCUMENTO.DOCCOD = DEVOLUCAO.DEVCOD)
INNER JOIN TROCA
  ON (DOCUMENTO.DOCCOD = TROCA.TRCCOD)
  AND (DOCUMENTO.LOJCOD = TROCA.LOJCOD)
  AND (TROCA.TRCCOD = DEVOLUCAO.DEVCOD)
  AND (TROCA.LOJCOD = DEVOLUCAO.LOJCOD)
INNER JOIN (SELECT
  LOJCOD,
  DEVCOD,
  REFPLU,
  SUM(ITRVLR) AS ITRVLR,
  SUM(COALESCE(ITRDCN, 0)) AS ITRDCN,
  SUM(ITRQTD) AS ITRQTD
FROM ITEM_DEVOLUCAO
GROUP BY LOJCOD,
         DEVCOD,
         REFPLU
UNION
SELECT
  ENF.LOJCOD,
  ENF.TRCCOD,
  IE.REFPLU,
  SUM(IE.ITEVLRTOT * -1) AS ITRVLR,
  SUM(COALESCE(IE.ITEVLRDCN, 0)) AS ITRDCN,
  SUM(IE.ITEQTDEMB * -1) AS ITRQTD
FROM ITEM_ENTRADA IE
INNER JOIN ESTOQUE_NOTA_FISCAL ENF
  ON ENF.LOJCOD = IE.LOJCOD
  AND ENF.DOCCOD = IE.ENTCOD
  AND ENF.REFPLU = IE.REFPLU
GROUP BY ENF.LOJCOD,
         ENF.TRCCOD,
         IE.REFPLU) DV
  ON DOCUMENTO.LOJCOD = DV.LOJCOD
  AND DOCUMENTO.DOCCOD = DV.DEVCOD
WHERE (DOCUMENTO.DOCDATEMI BETWEEN '2019/10/28' AND '2019/11/27')
AND (DOCUMENTO.DOCSTA = 'E')
AND (DOCUMENTO.ORICOD <> '065')
GROUP BY DOCUMENTO.LOJCOD,
         DOCUMENTO.DOCCOD
HAVING SUM(DV.ITRQTD) >
0) AS CONSULTA_TROCA
GROUP BY LOJCOD) AS CONSULTA_TROCA
  ON CONSULTA_TROCA.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  DOCUMENTO.LOJCOD,
  COUNT(*) AS PENDENCIA
FROM DEVOLUCAO
INNER JOIN DOCUMENTO
  ON DEVOLUCAO.LOJCOD =
  DOCUMENTO.LOJCOD
  AND DEVOLUCAO.DEVCOD = DOCUMENTO.DOCCOD
WHERE (DOCUMENTO.DOCDATEMI BETWEEN '2019/10/28' AND '2019/11/27')
AND (DOCUMENTO.DOCSTA = 'E')
AND (DOCUMENTO.ORICOD <> '065')
AND NOT EXISTS (SELECT
  *
FROM TROCA
WHERE TROCA.TRCCOD = DEVOLUCAO.DEVCOD
AND TROCA.LOJCOD = DEVOLUCAO.LOJCOD)
AND EXISTS (SELECT
  *
FROM ITEM_DEVOLUCAO ITD
INNER JOIN REFERENCIA R
  ON ITD.REFPLU = R.REFPLU
WHERE R.REFCMP <> 'K'
AND ITD.DEVCOD = DEVOLUCAO.DEVCOD
AND ITD.LOJCOD = DEVOLUCAO.LOJCOD
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL ENF
WHERE ENF.DEVCOD = ITD.DEVCOD
AND ENF.LOJCOD = ITD.LOJCOD
AND ENF.REFPLU = ITD.REFPLU))
GROUP BY DOCUMENTO.LOJCOD) AS CONSULTA_DEVOLUCAO
  ON CONSULTA_DEVOLUCAO.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  LOJCOD,
  COUNT(REQCOD) AS PENDENCIA
FROM (SELECT
  REQ_CONSUMO_ATENDIMENTO.LOJCOD,
  REQ_CONSUMO_ATENDIMENTO.REQCOD
FROM REQ_CONSUMO_EFETIVACAO
INNER JOIN REQ_CONSUMO_ATENDIMENTO
  ON REQ_CONSUMO_ATENDIMENTO.LOJCOD = REQ_CONSUMO_EFETIVACAO.LOJCOD
  AND REQ_CONSUMO_ATENDIMENTO.RCECOD = REQ_CONSUMO_EFETIVACAO.RCECOD
WHERE (REQ_CONSUMO_EFETIVACAO.RCEDAT BETWEEN '2019/10/28' AND
'2019/11/27')
AND EXISTS (SELECT
  *
FROM REQUISICAO_CONSUMO RC
WHERE RC.REQCOD = REQ_CONSUMO_ATENDIMENTO.REQCOD
AND RC.LOJCOD = REQ_CONSUMO_ATENDIMENTO.LOJCOD)
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL
WHERE ESTOQUE_NOTA_FISCAL.LOJCOD = REQ_CONSUMO_ATENDIMENTO.LOJCOD
AND ESTOQUE_NOTA_FISCAL.REQCOD = REQ_CONSUMO_ATENDIMENTO.REQCOD
AND ESTOQUE_NOTA_FISCAL.RCECOD = REQ_CONSUMO_EFETIVACAO.RCECOD
AND ESTOQUE_NOTA_FISCAL.REFPLU = REQ_CONSUMO_ATENDIMENTO.REFPLU)
GROUP BY REQ_CONSUMO_ATENDIMENTO.REQCOD,
         REQ_CONSUMO_ATENDIMENTO.LOJCOD) AS CONSULTA_REQUISICAO_CONSUMO
GROUP BY LOJCOD) AS CONSULTA_REQUISICAO_CONSUMO
  ON CONSULTA_REQUISICAO_CONSUMO.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  PC.LOJCOD,
  COUNT(PC.PCMCOD) AS PENDENCIA
FROM PRODUCAO_COMPOSTO PC
WHERE PC.PCMDAT BETWEEN '2019/10/28' AND '2019/11/27'
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL ENF
INNER JOIN V_ENTRADA D
  ON D.LOJCOD = ENF.LOJCOD
  AND D.DOCCOD = ENF.DOCCOD
WHERE ENF.PCMCOD = PC.PCMCOD
AND ENF.LOJCOD = PC.LOJCOD)
GROUP BY PC.LOJCOD) AS CONSULTA_PRODUCAO_COMPOSTO
  ON CONSULTA_PRODUCAO_COMPOSTO.LOJCOD = LOJ.LOJCOD
LEFT JOIN (SELECT
  PR.LOJCOD,
  COUNT(PR.PRECOD) AS PENDENCIA
FROM PRODUCAO_RENDIMENTO PR
INNER JOIN V_FUNCIONARIO F
  ON F.FUNCOD = PR.FUNCOD
WHERE PR.PREDAT BETWEEN '2019/10/28' AND '2019/11/27'
AND NOT EXISTS (SELECT
  *
FROM ESTOQUE_NOTA_FISCAL ENF
INNER JOIN V_ENTRADA D
  ON D.LOJCOD = ENF.LOJCOD
  AND D.DOCCOD = ENF.DOCCOD
WHERE ENF.PRECOD = PR.PRECOD)
AND EXISTS (SELECT
  *
FROM ITEM_RENDIMENTO_PRODUZIDO IRP
WHERE IRP.LOJCOD = PR.LOJCOD
AND IRP.PRECOD = PR.PRECOD)
GROUP BY PR.LOJCOD) AS CONSULTA_RENDIMENTO
  ON CONSULTA_RENDIMENTO.LOJCOD = LOJ.LOJCOD
WHERE (CONSULTA_INVENTARIO.PENDENCIA > 0
OR CONSULTA_AJUSTE.PENDENCIA > 0
OR CONSULTA_QUEBRA.PENDENCIA > 0
OR CONSULTA_TROCA.PENDENCIA > 0
OR CONSULTA_DEVOLUCAO.PENDENCIA > 0
OR CONSULTA_REQUISICAO_CONSUMO.PENDENCIA > 0
OR CONSULTA_PRODUCAO_COMPOSTO.PENDENCIA > 0
OR CONSULTA_RENDIMENTO.PENDENCIA > 0)