BEGIN TRAN

SET DATEFORMAT DMY

update 
  ITEM_SAIDA 
set 
  ITSNATPIS = NIP.NIPNATRECPISCOFINS,
  ITSNATCOFINS = NIP.NIPNATRECPISCOFINS,
  ITSCSTPIS = IAP.IFASITTRBSAI,
  ITSCSTCOFINS = IAC.IFASITTRBSAI
from
  ITEM_SAIDA I
  INNER JOIN V_SAIDA S ON S.LOJCOD = I.LOJCOD AND S.SAICOD = I.SAICOD
  INNER JOIN OPERACAO O ON O.OPECOD = S.OPECOD
  INNER JOIN LOJA L ON L.LOJCOD = I.LOJCOD
  INNER JOIN REFERENCIA R ON R.REFPLU = I.REFPLU

  INNER JOIN FAT_PRO FPP ON FPP.PROCOD = R.PROCOD
  INNER JOIN IMPOSTO_FEDERAL IP ON IP.IMFCOD = FPP.IMFCOD AND IP.IMFTIP = '01'
  INNER JOIN IMPOSTO_FEDERAL_APLICACAO IAP ON IAP.IMFCOD = FPP.IMFCOD AND IAP.IFAREGFED = L.LOJREGFED AND IAP.IFATIP in ('A', 'S')
  INNER JOIN NATUREZA_IMPOSTO_PRODUTO NIP ON NIP.PROCOD = R.PROCOD AND NIP.NIPREGFED = IAP.IFAREGFED

  INNER JOIN FAT_PRO FPC ON FPC.PROCOD = R.PROCOD
  INNER JOIN IMPOSTO_FEDERAL IC ON IC.IMFCOD = FPC.IMFCOD AND IC.IMFTIP = '02'
  INNER JOIN IMPOSTO_FEDERAL_APLICACAO IAC ON IAC.IMFCOD = FPC.IMFCOD AND IAC.IFAREGFED = L.LOJREGFED AND IAC.IFATIP in ('A', 'S')
where 
  OPEGERIMPFED = 'S' AND I.ITSDOCDATEMI >= '01/06/2016'

update 
  ITEM_ENTRADA 
set 
  ITENATPIS = NIP.NIPNATRECPISCOFINS,
  ITENATCOFINS = NIP.NIPNATRECPISCOFINS,
  ITECSTPIS = IAP.IFASITTRBENT,
  ITECSTCOFINS = IAC.IFASITTRBENT
from
  ITEM_ENTRADA I
  INNER JOIN V_ENTRADA E ON E.LOJCOD = I.LOJCOD AND E.ENTCOD = I.ENTCOD
  INNER JOIN OPERACAO O ON O.OPECOD = E.OPECOD
  INNER JOIN LOJA L ON L.LOJCOD = I.LOJCOD
  INNER JOIN REFERENCIA R ON R.REFPLU = I.REFPLU

  INNER JOIN FAT_PRO FPP ON FPP.PROCOD = R.PROCOD
  INNER JOIN IMPOSTO_FEDERAL IP ON IP.IMFCOD = FPP.IMFCOD AND IP.IMFTIP = '01'
  INNER JOIN IMPOSTO_FEDERAL_APLICACAO IAP ON IAP.IMFCOD = FPP.IMFCOD AND IAP.IFAREGFED = L.LOJREGFED AND IAP.IFATIP in ('A', 'E')
  INNER JOIN NATUREZA_IMPOSTO_PRODUTO NIP ON NIP.PROCOD = R.PROCOD AND NIP.NIPREGFED = IAP.IFAREGFED

  INNER JOIN FAT_PRO FPC ON FPC.PROCOD = R.PROCOD
  INNER JOIN IMPOSTO_FEDERAL IC ON IC.IMFCOD = FPC.IMFCOD AND IC.IMFTIP = '02'
  INNER JOIN IMPOSTO_FEDERAL_APLICACAO IAC ON IAC.IMFCOD = FPC.IMFCOD AND IAC.IFAREGFED = L.LOJREGFED AND IAC.IFATIP in ('A', 'E')

where 
  OPEGERIMPFED = 'S' AND E.ENTDATENT >= '01/06/2016'

COMMIT



select * from NATUREZA_IMPOSTO_PRODUTO