begin tran
update 
  ESTOQUE
set
  ESTTOT = ISNULL(EXT.FISCAL, 0) + ISNULL(EXT.FISICO, 0),
  ESTFSC = ISNULL(EXT.FISICO, 0),
  ESTFSL = ISNULL(EXT.FISCAL, 0)
from
  ESTOQUE E
  left join(
	select 
	  LOJCOD,
	  LOCCOD,
	  REFPLU,
	  SUM(ISNULL(EXTQTDFSC, 0)) AS FISICO,
	  SUM(ISNULL(EXTQTDFSL, 0)) AS FISCAL
	from  
	  EXTRATO_ESTOQUE with(nolock)
	group by 
	  LOJCOD,
	  LOCCOD,
	  REFPLU
  ) EXT on EXT.LOJCOD = E.LOJCOD and EXT.LOCCOD = E.LOCCOD AND EXT.REFPLU = E.REFPLU

update
  ESTOQUE_LOJA
set
  ESTLOJFSL = E.FISCAL,
  ESTLOJFSC = E.FISICO
from
  ESTOQUE_LOJA EL 
  left join (
    select 
	  E.LOJCOD,
	  E.REFPLU,
	  sum(isnull(E.ESTFSL, 0)) AS FISCAL,
	  sum(isnull(E.ESTFSC, 0)) AS FISICO
	from 
	  ESTOQUE E
	group by 
	  E.LOJCOD,
	  E.REFPLU
  ) E ON E.LOJCOD = EL.LOJCOD AND E.REFPLU = EL.REFPLU


  UPDATE ESTOQUE_LOJA
    SET 
      ESTLOJEMCMPFSC = DADOS.COMPRA_FISICO,  
      ESTLOJEMCMPFSL = DADOS.COMPRA_FISCAL, 
  
      ESTLOJEMVDAFSC = DADOS.VENDA_FISICO + DADOS.PREVENDA_FISICO,
      ESTLOJEMVDAFSL = DADOS.VENDA_FISCAL + DADOS.PREVENDA_FISCAL, 
      
      ESTLOJEMTRFFSC = DADOS.TRANSF_SAI_FISICO, 
      ESTLOJEMTRFFSL = DADOS.TRANSF_SAI_FISCAL, 
      
      ESTLOJEMTRFENTFSC = DADOS.TRANSF_ENT_FISICO, 
      ESTLOJEMTRFENTFSL = DADOS.TRANSF_ENT_FISCAL 
      
    FROM ESTOQUE_LOJA 
       INNER JOIN
       (    
          SELECT 
  			L.LOJCOD, 
  			R.REFPLU, 
  			SUM(ISNULL(COMPRA.FISCAL, 0) + ISNULL(COMPRA.FISICO, 0)) AS COMPRA, 
  			SUM(ISNULL(COMPRA.FISICO, 0)) AS COMPRA_FISICO, 
            SUM(ISNULL(COMPRA.FISCAL, 0)) AS COMPRA_FISCAL, 
              
            SUM(ISNULL(VENDA.FISCAL, 0) + ISNULL(VENDA.FISICO, 0)) AS VENDA, 
            SUM(ISNULL(VENDA.FISICO, 0)) AS VENDA_FISICO, 
            SUM(ISNULL(VENDA.FISCAL, 0)) AS VENDA_FISCAL, 
             
            SUM(ISNULL(TRANS_ENT.FISCAL, 0) + ISNULL(TRANS_ENT.FISICO, 0)) AS TRANSF_ENT, 
            SUM(ISNULL(TRANS_ENT.FISICO, 0)) AS TRANSF_ENT_FISICO, 
            SUM(ISNULL(TRANS_ENT.FISCAL, 0)) AS TRANSF_ENT_FISCAL, 
              
            SUM(ISNULL(TRANS_SAI.FISCAL, 0) + ISNULL(TRANS_SAI.FISICO, 0)) AS TRANSF_SAI, 
            SUM(ISNULL(TRANS_SAI.FISICO, 0)) AS TRANSF_SAI_FISICO, 
            SUM(ISNULL(TRANS_SAI.FISCAL, 0)) AS TRANSF_SAI_FISCAL,
              
            SUM(ISNULL(PREVENDA.FISCAL, 0) + ISNULL(PREVENDA.FISICO, 0)) AS PREVENDA, 
            SUM(ISNULL(PREVENDA.FISICO, 0)) AS PREVENDA_FISICO, 
            SUM(ISNULL(PREVENDA.FISCAL, 0)) AS PREVENDA_FISCAL
              
             FROM 
               REFERENCIA R CROSS JOIN LOJA L
                  LEFT JOIN
                  (
  
  					SELECT 
  						P.LOJCOD, 
  						I.REFPLU, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'S' THEN (PD.PCDQTD - ISNULL(PD.PCDQTDATE, 0)) * IPCQTDITEEMB ELSE 0 END), 0)) AS FISCAL, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'N' THEN (PD.PCDQTD - ISNULL(PD.PCDQTDATE, 0)) * IPCQTDITEEMB ELSE 0 END), 0)) AS FISICO 
  					FROM 
  						PEDIDO_COMPRA P 
  							INNER JOIN ITEM_PEDIDO_COMPRA I ON P.LOJCOD = I.LOJCOD AND P.PDCCOD = I.PDCCOD 
  							INNER JOIN PEDIDO_COMPRA_DISTRIBUICAO PD ON (I.LOJCOD = PD.LOJCOD AND I.PDCCOD = PD.PDCCOD AND I.REFPLU = PD.REFPLU)
  							INNER JOIN OPERACAO O ON P.OPECOD = O.OPECOD 
  					WHERE 
  						OPEEST = 'P' AND 
  						P.PDCSTA IN ('A', 'P') AND 
  						COALESCE(PD.PCDQTDATE, 0) < COALESCE(PD.PCDQTD, 0)
  					GROUP BY 
  						P.LOJCOD, I.REFPLU                  
                  ) AS COMPRA ON COMPRA.LOJCOD = L.LOJCOD AND COMPRA.REFPLU = R.REFPLU
                  
                  LEFT JOIN
                  (
  
  					SELECT 
  						P.LOJCOD, 
  						I.REFPLU, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'S' THEN (PD.PVDQTD - ISNULL(PD.PVDQTDATE, 0)) * IPVQTDITEEMB ELSE 0 END), 0)) AS FISCAL, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'N' THEN (PD.PVDQTD - ISNULL(PD.PVDQTDATE, 0)) * IPVQTDITEEMB ELSE 0 END), 0)) AS FISICO 
  					FROM 
  						PEDIDO_VENDA P 
  							INNER JOIN ITEM_PEDIDO_VENDA I ON P.LOJCOD = I.LOJCOD AND P.PDVCOD = I.PDVCOD 
  							INNER JOIN PEDIDO_VENDA_DISTRIBUICAO PD ON (I.LOJCOD = PD.LOJCOD AND I.PDVCOD = PD.PDVCOD AND I.REFPLU = PD.REFPLU)
  							INNER JOIN OPERACAO O ON P.OPECOD = O.OPECOD 
  					WHERE 
  						OPEEST = 'P' AND 
  						P.PDVSTA IN ('A', 'P') AND 
  						COALESCE(PD.PVDQTDATE, 0) < COALESCE(PD.PVDQTD, 0)
  					GROUP BY 
  						P.LOJCOD, I.REFPLU                  
                  ) AS VENDA ON VENDA.LOJCOD = L.LOJCOD AND VENDA.REFPLU = R.REFPLU
                  
                  LEFT JOIN
                  (
  					SELECT 
  						P.LOJCOD, 
  						I.REFPLU, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'S' THEN CASE WHEN (P.PDTSTA = 'E' AND PA.PDTSTACNF = 'N') THEN ISNULL(PA.PTAQTD, 0) * IPTQTDITEEMB ELSE (I.IPTQTDEMB - ISNULL(I.IPTQTDATE, 0)) * IPTQTDITEEMB END ELSE 0 END), 0)) AS FISCAL, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'N' THEN CASE WHEN (P.PDTSTA = 'E' AND PA.PDTSTACNF = 'N') THEN ISNULL(PA.PTAQTD, 0) * IPTQTDITEEMB ELSE (I.IPTQTDEMB - ISNULL(I.IPTQTDATE, 0)) * IPTQTDITEEMB END ELSE 0 END), 0)) AS FISICO 
  					FROM 
  						PEDIDO_TRANSFERENCIA P 
  							INNER JOIN ITEM_PEDIDO_TRANSFERENCIA I ON P.LOJCOD = I.LOJCOD AND P.PDTCOD = I.PDTCOD 
  							INNER JOIN OPERACAO O ON P.OPECOD = O.OPECOD 
  							LEFT JOIN PEDIDO_TRANSFERENCIA_ATENDIMENTO PA ON PA.LOJCOD = I.LOJCOD AND PA.PDTCOD = I.PDTCOD AND PA.REFPLU = I.REFPLU
  					WHERE 
  						OPEEST = 'P' AND 
  					    (P.PDTSTA IN ('A', 'P') OR ((P.PDTSTA = 'E') AND (PA.PDTSTACNF = 'N') AND NOT EXISTS (SELECT * FROM ESTORNO_DOCUMENTO E WHERE E.DOCCODORI = PA.SAICOD AND E.LOJCOD = PA.LOJCODSAI)))

  					GROUP BY 
  						P.LOJCOD, I.REFPLU                  
                  ) AS TRANS_ENT ON TRANS_ENT.LOJCOD = L.LOJCOD AND TRANS_ENT.REFPLU = R.REFPLU
                  
                  LEFT JOIN
                  (
  					SELECT 
  						P.LOJCODATE, 
  						I.REFPLU, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'S' THEN (I.IPTQTDEMB - ISNULL(I.IPTQTDATE, 0)) * IPTQTDITEEMB ELSE 0 END), 0)) AS FISCAL, 
  						SUM(ISNULL((CASE WHEN OPECARFIS = 'N' THEN (I.IPTQTDEMB - ISNULL(I.IPTQTDATE, 0)) * IPTQTDITEEMB ELSE 0 END), 0)) AS FISICO 
  					FROM 
  						PEDIDO_TRANSFERENCIA P 
  							INNER JOIN ITEM_PEDIDO_TRANSFERENCIA I ON P.LOJCOD = I.LOJCOD AND P.PDTCOD = I.PDTCOD 
  							INNER JOIN OPERACAO O ON P.OPECOD = O.OPECOD 
  					WHERE 
  						OPEEST = 'P' AND 
  						P.PDTSTA IN ('A', 'P') AND 
  						COALESCE(I.IPTQTDATE, 0) < COALESCE(I.IPTQTDEMB, 0)
  					GROUP BY 
  						P.LOJCODATE, I.REFPLU                  
  						
                  ) AS TRANS_SAI ON TRANS_SAI.LOJCODATE = L.LOJCOD AND TRANS_SAI.REFPLU = R.REFPLU
                  
                  LEFT JOIN
                  (
                  SELECT 
						I.LOJCOD, 
						REFPLU, 
						SUM(ITEPRVATEQTD) AS FISCAL, 
						0 AS FISICO 
                  FROM 
					 ITEM_PREVENDA_ATENDIMENTO I inner join PREVENDA P ON I.PRVCOD = P.PRVCOD 
				  WHERE
				     PRVFAT = 'N' AND 
				     PRVRSVEST = 'S' AND
				     PRVSTA = 'E' AND
					 (ORICOD IS NULL OR ORICOD <> '104') AND
				     PRVDATVNC >= (SELECT MAX(ABRDAT) FROM ABERTURA)
					GROUP BY 
						I.LOJCOD, REFPLU 
                  ) AS PREVENDA ON PREVENDA.LOJCOD = L.LOJCOD AND PREVENDA.REFPLU = R.REFPLU
                  
      GROUP BY L.LOJCOD, R.REFPLU
    ) AS DADOS ON DADOS.LOJCOD = ESTOQUE_LOJA.LOJCOD AND DADOS.REFPLU = ESTOQUE_LOJA.REFPLU  
commit