SELECT
  VT.NUM_DOC,
  VT.NUM_CHEQUE,
  VT.BANCO,
  VT.AGENCIA,
  VT.CONTA,
  VT.BORDERO
FROM V_TITULO_REC AS VT
INNER JOIN (SELECT
  NUM_DOC,
  NUM_CHEQUE,
  BANCO,
  AGENCIA,
  CONTA,
  COUNT(*) AS 'CONT'
FROM V_TITULO_REC
GROUP BY NUM_DOC,
         NUM_CHEQUE,
         BANCO,
         AGENCIA,
         CONTA
HAVING COUNT(*) >= 2) AS CHEQUE
  ON VT.NUM_DOC = CHEQUE.NUM_DOC
  AND VT.NUM_CHEQUE = CHEQUE.NUM_CHEQUE
  AND VT.BANCO = CHEQUE.BANCO
  AND VT.AGENCIA = CHEQUE.AGENCIA
  AND VT.CONTA = CHEQUE.CONTA
WHERE VT.BORDERO <> '-'



