CREATE VIEW V_MANUTENCAO_LANC_CONTABEIS AS
SELECT
  L.ESTCOD AS Estabelecimento,
  O.ORICNTDES AS Origem,
  L.LCTDAT AS Data,
  C.CLCTCTACTB AS Conta,
  L.LCTVLRTOT AS Valor,
  C.CLCTTIP AS Natureza,
  L.LCTHSTCMP AS Historico,
  C.CLCTHSTCMP AS Complemento
FROM LANCAMENTO_CONTABIL L 
INNER JOIN ORIGEM_LANCAMENTO_CONTABIL O
  ON O.ORICNTCOD = L.ORICNTCOD
INNER JOIN COMPLEMENTO_LANCAMENTO_CONTABIL C
  ON L.LCTCOD = C.LCTCOD

--ENTIDADES
INSERT INTO ENTIDADE (ENTNOM,ENTTIT)  VALUES ('V_MANUTENCAO_LANC_CONTABEIS', 'Relatório de Manutenção Contábil')

--ATRIBUTOS	
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Estabelecimento','Código estabalecimento','S',4,'9999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Origem','Descrição','S',100,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Data','Data','D',0,'99/99/9999;1;_','N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Conta','Conta contábil','S',15,'999999999999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Valor','Valor total','F',12,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Natureza','Tipo','S',7,'9999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Historico','Histórico','S',80,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_MANUTENCAO_LANC_CONTABEIS','Complemento','Complemento','S',100,NULL,'N')


