SELECT
  V.LOJCOD		AS LOJA,
  I.REFPLU		AS PLU, 
  P.PRODES		AS DESCRICAO,
  F.FORCOD		AS FORNECEDOR,
  A.AGEEST		AS ESTADO,
  I.TRBID		AS TRIBUTACAO,
  I.ITEVLRICMS	AS ALIQUOTA,
  P.SECCOD		AS SECAO,
  P.GRPCOD		AS GRUPO,
  P.SBGCOD		AS SUBGRUPO,
  E.ESTLOJTOT	AS ESTOQUE
FROM 
V_ULTIMA_ENTRADA_LOJA		V
INNER JOIN AGENTE			A	ON V.AGECOD = A.AGECOD
INNER JOIN FORNECEDOR		F	ON A.AGECOD = F.AGECOD
INNER JOIN ITEM_ENTRADA		I	ON V.ENTCOD = I.ENTCOD AND V.LOJCOD = I.LOJCOD AND V.REFPLU = I.REFPLU
INNER JOIN REFERENCIA		R	ON R.REFPLU = I.REFPLU
INNER JOIN PRODUTO			P	ON P.PROCOD = R.PROCOD
INNER JOIN ESTOQUE_LOJA		E	ON E.REFPLU = I.REFPLU AND E.LOJCOD = I.LOJCOD 
WHERE E.ESTLOJTOT > 0