--ALTER VIEW V_MOV_CONTA AS
SELECT
LOJCOD						AS LOJ,
CCLDATLAN					AS DATA,
CTCCOD						AS CONTA,
CCLVLR						AS VLR,
CASE HPACOD
WHEN '001' THEN 'ESTORNO CREDITO'
WHEN '002' THEN 'ESTORNO DEBITO'
WHEN '003' THEN 'PAGO'
WHEN '004' THEN 'RECEBIDO'
WHEN '005' THEN 'BORDERO Nº'
WHEN '006' THEN 'DESCONTO BORDERO Nº'
WHEN '007' THEN 'COMPENSADO CHEQUE A PAGAR Nº'
WHEN '008' THEN 'COMPENSADO CHEQUE A RECEBER Nº'
WHEN '009' THEN 'DEBITO'
WHEN '010' THEN 'CREDITO'
WHEN '011' THEN 'TRANSFERENCIA C'
WHEN '012' THEN 'TRANSFERENCIA D'
WHEN '013' THEN 'SANGRIA DIARIA CX'
WHEN '014' THEN 'DEVOLUÇÃO DE DINHEIRO'
WHEN '015' THEN 'REFORCO DE CAIXA'
WHEN '016' THEN 'TARIFAS BANCÁRIAS'
WHEN '017' THEN 'APLICAÇÃO CONTAMAX C'
WHEN '018' THEN 'APLICAÇAO CONTAMAX D'
WHEN '019' THEN 'AJUSTE DE CAIXA TROCO- CREDITO'
WHEN '020' THEN 'AJUSTE DE CAIXA TROCO - DÉBITO'
WHEN '021' THEN 'DEPOSITO SANGRIAS'
WHEN '022' THEN 'NÃO USAR'
WHEN '023' THEN 'NÃO USAR'
WHEN '024' THEN 'NÃO USAR'
WHEN '025' THEN 'QUEBRA DE CAIXA'
WHEN '026' THEN 'SOBRA DE CAIXA'
WHEN '027' THEN 'NÃO USAR'
WHEN '028' THEN 'NÃO USAR'
WHEN '029' THEN 'NÃO USAR'
WHEN '030' THEN 'NÃO USAR'
WHEN '031' THEN 'NÃO USAR'
WHEN '032' THEN 'NÃO USAR'
WHEN '033' THEN 'NÃO USAR'
WHEN '034' THEN 'NÃO USAR'
WHEN '035' THEN 'NÃO USAR'
WHEN '036' THEN 'ESTACIONAMENTO'
WHEN '037' THEN 'RETIRADA DO SR. MARCILIO'
WHEN '039' THEN 'COMPRA'
WHEN '040' THEN 'RETIRADA WASHINGTON'
END						AS HIST,
CCLCOMHIS				AS CPM,
PLCCOD					AS PLACONTA
FROM CONTA_CORRENTE_LANCAMENTO 


--ENTIDADES
INSERT INTO ENTIDADE (ENTNOM,ENTTIT)  VALUES ('V_MOV_CONTA', 'Relatório de Movimentação de Contas')

--ATRIBUTOS	
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ)			VALUES ('V_MOV_CONTA','LOJ','Loja','S',6,'999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ)			VALUES ('V_MOV_CONTA','DATA','Data lançamento','D',0,'99/99/9999;1;_','N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ)			VALUES ('V_MOV_CONTA','CONTA','Conta corrente','S',4,NULL,'S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ)	VALUES ('V_MOV_CONTA','VLR','Valor','F',12,4,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ)			VALUES ('V_MOV_CONTA','HIST','Histórico padrão','S',40,NULL,'S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ)			VALUES ('V_MOV_CONTA','CPM','Complemento histórico','S',4000,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ)			VALUES ('V_MOV_CONTA','PLACONTA','Plano Contas','S',6,'999999;0;_','S')



