CREATE VIEW V_VENDA_HOLDING AS
SELECT 
CL.HOLCOD AS HOLDING,
CL.CLICOD AS CODIGO_CLIENTE,
CL.AGEDES AS DESCRICAO_CLIENTE,
ISNULL (F.FUNAPE,'') AS VENDEDOR,
CL.CLIDCNFIN AS DESCONTO_FINANCEIRO,
R.REFCOD AS PLU,
R.REFDES AS DESCRICAO_PLU,
P.SECCOD AS SECAO,
I.ITSVLREMBREA AS PRECO_VENDA,
I.ITSQTDEMB AS QUANTIDADE,
I.ITSTOTFAT AS TOTAL,
C.CSTMED AS CUSTO_MEDIO,
CONVERT(VARCHAR, I.ITSDATMOV, 120) AS DATA_MOV
FROM  V_SAIDA S
INNER JOIN ITEM_SAIDA I ON S.LOJCOD = I.LOJCOD AND S.SAICOD = I.SAICOD
INNER JOIN CUSTO C ON I.LOJCOD = C.LOJCOD AND I.REFPLU = C.REFPLU
LEFT JOIN V_CLIENTE CL ON S.AGECOD = CL.AGECOD
LEFT JOIN FUNCIONARIO F ON CL.FUNCOD = F.FUNCOD
INNER JOIN REFERENCIA R ON I.REFPLU = R.REFPLU
INNER JOIN PRODUTO P ON R.PROCOD = P.PROCOD
LEFT JOIN FINALIDADE_PRODUTO_LOJA FPL WITH (NOLOCK)
ON FPL.PROCOD = P.PROCOD AND FPL.LOJCOD = I.LOJCOD
WHERE 
I.LOJCOD IN ('000002')
AND I.ITSOPECOD IN ('000004', '000020')
AND COALESCE(FPL.FPLTIP, P.PROTIP) IN ('1')
AND I.ITSDOCSTA = 'E'
AND I.ITSTIP = 'E'
AND (I.ITSDOCSTANFE IS NULL
OR I.ITSDOCSTANFE = 'A')
GROUP BY
CL.HOLCOD,
CL.CLICOD,
CL.AGEDES,
F.FUNAPE,
CL.CLIDCNFIN,
R.REFCOD,
R.REFDES,
P.SECCOD,
I.ITSVLREMBREA,
I.ITSQTDEMB,
I.ITSTOTFAT,
C.CSTMED,
I.ITSDATMOV



 INSERT INTO ENTIDADE (ENTNOM, ENTTIT) VALUES ('V_VENDA_HOLDING', 'Relatório de Holding')


 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','HOLDING','Holding','S',3,'','999;0;_','S','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','CODIGO_CLIENTE','Código cliente','S',6,'','999999;0;_','S','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','DESCRICAO_CLIENTE','Descrição', 'S', 80,'','','N','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','VENDEDOR','Vendedor','S',80,'','','N','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','DESCONTO_FINANCEIRO','Valor desconto','F',12,4,'','N',',0.0000')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','PLU','PLU','S',7,'','','S','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','DESCRICAO_PLU','Descrição','S',120,'','','N','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','SECAO','Seção','S',2,'','99;0;_','S','')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','PRECO_VENDA','Vlr Embalagem','F', 12, 4,'','N',',0.0000')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','QUANTIDADE','Quantidade embalagem','F', 12, 3,'','N',',0.000')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','TOTAL','Faturamento','F', 15, 6,'','N',',0.000000')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','CUSTO_MEDIO','Custo Médio','F', 18, 6,'','N',',0.000000')
 INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB)
 VALUES ('V_VENDA_HOLDING','DATA_MOV','Data movimentação','D', 0, null,'99/99/9999;1;_','N','DD/MM/YYYY')







