CREATE VIEW V_PRODUTO_CEST AS 
SELECT
  R.REFCOD AS PLU,
  R.REFDES AS DESCRICAO,
  R.REFNCM AS NCM,
  COALESCE (R.CSTCOD, 'SEM CEST') AS CEST
FROM REFERENCIA R
LEFT JOIN NCM_CEST N
  ON R.REFNCM = N.NCMCOD
WHERE R.CSTCOD IS NULL
GROUP BY R.REFCOD,
         R.REFDES,
         R.REFNCM,
         R.CSTCOD


--ENTIDADES
INSERT INTO ENTIDADE (ENTNOM,ENTTIT)  VALUES ('V_PRODUTO_CEST', 'Produtos sem CEST ')

--ATRIBUTOS 
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_PRODUTO_CEST','PLU','Código PLU','S',7,'','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_PRODUTO_CEST','DESCRICAO','Descrição','S',120,'','N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_PRODUTO_CEST','NCM','Código NCM','S',8,'99999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_PRODUTO_CEST','CEST','Código CEST','S',7,'99.999.99;0;_','S')





