CREATE VIEW V_LIMITE_CLIENTE AS
SELECT
  V_CLIENTE.CLICOD,
  V_CLIENTE.AGEDES
FROM V_CLIENTE
WHERE NOT EXISTS (SELECT
  *
FROM LIMITE_CREDITO_CLIENTE
WHERE V_CLIENTE.CLICOD = LIMITE_CREDITO_CLIENTE.CLICOD)

--ENTIDADES
INSERT INTO ENTIDADE (ENTNOM,ENTTIT)  VALUES ('V_LIMITE_CLIENTE', 'Relatório Clientes sem Limite de Crédito')

--ATRIBUTOS   
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_LIMITE_CLIENTE','CLICOD','Código cliente','S',6,'999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_LIMITE_CLIENTE','AGEDES','Descrição','S',80,'','N')
