CREATE VIEW V_TITULO_REC AS
SELECT
 TF.LOJCOD		AS 'LOJA',
 A.AGEDES		AS 'NOME',
 A.AGECID		AS 'CIDADE',
 A.AGEEST		AS 'ESTADO',
 C.CLICOD		AS 'COD_CLIENTE',
 C.CLILIMCRE	AS 'LIM_TOTAL',
 C.CLILIMUTL	AS 'LIM_UTILIZADO',
 ISNULL((SELECT TOP 1
    AA.AGECOD + '-' + AA.AGEFAN
  FROM AGENTE AA
  WHERE AA.AGECOD = TF.AGECODREC), '*** SEM AGENTE RECEBEDOR DEFINIDO ***')	AS 'AGE_RECEBEDOR',
 TD.TIPDOCDES	AS 'TIPO_DOC',
 TF.TIFNUMDOC	AS 'NUM_DOC',
 CASE TF.TIFSIT	
 WHEN 'A' THEN 'ABERTO'
 WHEN 'P' THEN 'PARC. LIQ'
 END AS 'SITUACAO',
 TF.TIFDATEMI	AS 'DAT_EMISS',
 TF.TIFDATVNC	AS 'DAT_VENC',
 TF.TIFVLRNOM	AS 'VLR_NOM',
 TF.TIFVLRDEV	AS 'VLR_DEV',
 TF.TIFJURDEV	AS 'JUROS',
 TF.TIFACRDEV	AS 'MULTA',
 TF.TIFVLRDEF	AS 'DESCONTO',
 COALESCE (TF.TIFOBS,'-')	AS 'OBS',
 COALESCE (CH.CHRCHQNUM, '-')	AS 'NUM_CHEQUE',
 COALESCE (CH.CHRNUMBCO, '-')	AS 'BANCO',
 COALESCE (CH.CHRNUMAGE, '-')	AS 'AGENCIA',
 COALESCE (CH.CHRNUMCTA, '-')	AS 'CONTA',
 COALESCE (B.BRDCOD, '-')		AS 'BORDERO'
FROM 
AGENTE A 
INNER JOIN CLIENTE C			ON A.AGECOD = C.AGECOD 
INNER JOIN TITULO_FINANCEIRO TF ON TF.AGECOD = A.AGECOD
INNER JOIN V_LOJA L				ON L.LOJCOD = TF.LOJCOD
LEFT JOIN V_TITULO_RECEBER TR	ON TR.LOJCOD = TF.LOJCOD AND TR.TRECOD = TF.TIFCOD
FULL JOIN V_CHEQUE_RECEBER CH	ON CH.TIFCOD = TF.TIFCOD
FULL JOIN ITEM_BORDERO B ON B.TRECOD = CH.TRECOD
INNER JOIN TIPO_DOCUMENTO TD ON TF.TIPDOCCOD = TD.TIPDOCCOD
WHERE TF.TIFSIT IN ('A','P') AND TF.TIFSTA <> 'X' AND ISNULL(TF.TIFSTA, 'N') = 'N'


--ENTIDADES
INSERT INTO ENTIDADE (ENTNOM,ENTTIT)  VALUES ('V_TITULO_REC', 'Relatório Detalhado de Títulos a Receber')

--ATRIBUTOS	
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','LOJA','Código da loja','S',6,'999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','NOME','Descrição','S',80,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','CIDADE','Cidade','S',50,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','ESTADO','Estado','S',2,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','COD_CLIENTE','Código cliente','S',6,'999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','LIM_TOTAL','Limite geral','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','LIM_UTILIZADO','Limite utilizado','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','AGE_RECEBEDOR','Código agente recebedor','S',6,'999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','TIPO_DOC','Descrição','S',20,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','NUM_DOC','Número documento','S',20,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','SITUACAO','Situação','S',9,'999999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','DAT_EMISS','Data emissão','D',0,'99/99/9999;1;_','N','DD/MM/YYYY')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','DAT_VENC','Data vencimento','D',0,'99/99/9999;1;_','N','DD/MM/YYYY')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','VLR_NOM','Valor nominal','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','VLR_DEV','Valor devido','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','JUROS','Juros devido','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','MULTA','Acréscimos devido','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRPRC,ATRMSK,ATRFMTZERESQ,ATRFMTEXB) VALUES ('V_TITULO_REC','DESCONTO','Valor desconto financeiro','F',12,4,NULL,'N',',0.0000')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','OBS','Observação','S',500,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','NUM_CHEQUE','Número cheque','S',10,'9999999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','BANCO','Número banco','S',3,'999999;0;_','S')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','AGENCIA','Número agência','S',5,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','CONTA','Número conta','S',10,NULL,'N')
INSERT INTO ATRIBUTO (ENTNOM,ATRNOM,ATRTIT,ATRTIP,ATRTMN,ATRMSK,ATRFMTZERESQ) VALUES ('V_TITULO_REC','BORDERO','Código borderô','S',6,'999999;0;_','S')
